---
title: "graph_power_spectra"
author: "Paul Bloom"
date: "7/9/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

```{r}
power_spectra = read_csv('../../data/rest_power_spectra.csv')
length(unique(power_spectra$frequency))
```


```{r}
power_spectra_long = power_spectra %>%
  pivot_longer(cols = c(0,1,2,3,4,5, 6)) %>%
  mutate(name = case_when(
    name == '0' ~ 'roll',
    name == '1' ~ 'pitch',
    name == '2' ~ 'yaw',
    name == '3' ~ 'dS',
    name == '4' ~ 'dL',
    name == '5' ~ 'dP',
  ))


fd_ranks = power_spectra_long %>%
  group_by(scan_id) %>%
  summarise(median_fd = median_fd[1]) %>%
  mutate(median_fd_rank = rank(1-median_fd)) %>%
  dplyr::select(-median_fd)


power_spectra_long = power_spectra_long %>%
  left_join(., fd_ranks, by = 'scan_id') 

cutoff = 2

power_spectra_z = power_spectra_long %>%
  group_by(scan_id, name) %>%
  mutate(pow_scaled = scale(10*log10(value)), 
         pow_scaled = case_when(pow_scaled > cutoff ~ cutoff,
                                pow_scaled < -1*cutoff ~ -1*cutoff,
                                pow_scaled >= -1*cutoff & pow_scaled <= cutoff ~ pow_scaled),
         pow_p = (pow_scaled + 2)/(max(pow_scaled) +2))


ggplot(power_spectra_z, aes(x = frequency, y = median_fd_rank, fill = pow_scaled)) +
  geom_tile() +
  facet_grid(~name) +
  theme_bw() +
  scale_fill_viridis_c() +
  labs(fill = 'Power (z-scored)', x = 'Frequency', y = 'Scams Ranked by FD') +
  theme(axis.text.y = element_blank())
```


# SB

```{r}
power_spectra = read_csv('../../../sb/data/rest_power_spectra.csv')
length(unique(power_spectra$frequency))
```


```{r}
power_spectra_long = power_spectra %>%
  pivot_longer(cols = c(0,1,2,3,4,5, 6)) %>%
  mutate(name = case_when(
    name == '0' ~ 'roll',
    name == '1' ~ 'pitch',
    name == '2' ~ 'yaw',
    name == '3' ~ 'dS',
    name == '4' ~ 'dL',
    name == '5' ~ 'dP',
  ))


fd_ranks = power_spectra_long %>%
  group_by(scan_id) %>%
  summarise(median_fd = median_fd[1]) %>%
  mutate(median_fd_rank = rank(1-median_fd)) %>%
  dplyr::select(-median_fd)


power_spectra_long = power_spectra_long %>%
  left_join(., fd_ranks, by = 'scan_id') 

cutoff = 2

power_spectra_z = power_spectra_long %>%
  group_by(scan_id, name) %>%
  mutate(pow_scaled = scale(10*log10(value)), 
         pow_scaled = case_when(pow_scaled > cutoff ~ cutoff,
                                pow_scaled < -1*cutoff ~ -1*cutoff,
                                pow_scaled >= -1*cutoff & pow_scaled <= cutoff ~ pow_scaled),
         pow_p = (pow_scaled + 2)/(max(pow_scaled) +2)) 

hist(power_spectra_z$pow_scaled)
 
ggplot(power_spectra_z, aes(x = frequency, y = median_fd_rank, fill = pow_scaled)) +
  geom_tile() +
  facet_grid(~name) +
  theme_bw() +
  scale_fill_viridis_c() +
  labs(fill = 'Power (z-scored)', x = 'Frequency', y = 'Scams Ranked by FD') #+
  #theme(axis.text.y = element_blank())
```